x-common-config: &common-config
  build:
    context: ./fad_backend
  volumes:
    - .:/app
  environment:
    DJANGO_DB_HOST: db
    DJANGO_DB_PORT: 5432
    DJANGO_DB_NAME: django_project
    DJANGO_DB_USER: django_user
    DJANGO_DB_PASSWORD: django_password
  depends_on:
    - db


services:
  web:
    container_name: fad-backend
    command: python fad_backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/swagger.json"]
      interval: 5s
      retries: 5
      timeout: 5s
    
    <<: *common-config
  
  frontend:
    container_name: fad-frontend
    command: >
       sh -c "npm install swagger-typescript-api && npx swagger-typescript-api generate -p http://web:8000/swagger.json -o src/api && npm run dev"
    build:
      context: ./fad_frontend
    ports:
      - "3000:3000"
    depends_on:
      web:
        condition: service_healthy

    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./fad_frontend:/fad_frontend
      - node_modules:/fad_frontend/node_modules



  migrate:    
    container_name: fad-migrate
    command: python fad_backend/manage.py migrate  # Run migrations
    profiles:
      - migration
    <<: *common-config
    

  make_migrations:
      container_name: make_migrations_fad
      command: python fad_backend/manage.py makemigrations 
      profiles:
        - make_migrations
      <<: *common-config
  

  add_app:
    container_name: make_migrations_fad
    working_dir: /app/fad_backend
    command: python manage.py startapp security
    profiles:
      - add_app
    <<: *common-config
    

  tests:
    container_name: tests
    working_dir: /app/fad_backend
    command: python manage.py test 
    profiles:
      - tests
    <<: *common-config
    
  
    
  db:
    image: postgres:15  # Use PostgreSQL 15 as the database image
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: django_project        # Name of the database
      POSTGRES_USER: django_user         # Database user
      POSTGRES_PASSWORD: django_password # Password for the user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  node_modules: