# Generated by Django 5.1.5 on 2025-04-03 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_group_calender_program_alter_program_atributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='portal.program'),
        ),
    ]
