# Generated by Django 5.1.5 on 2025-04-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_user_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_notifcation', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='portal.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.post')),
                ('link', models.URLField()),
            ],
            bases=('portal.post',),
        ),
        migrations.CreateModel(
            name='PostPdf',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portal.post')),
                ('file_name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
            bases=('portal.post',),
        ),
    ]
