# Generated by Django 5.1.5 on 2025-04-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_post_postlink_postpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='portal.program'),
        ),
    ]
