# Generated by Django 5.1.5 on 2025-04-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_post_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='atributes',
            new_name='attributes',
        ),
    ]
