# Generated by Django 5.1.5 on 2025-04-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_rename_atributes_program_attributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='atributes',
            new_name='attributes',
        ),
    ]
