# Generated by Django 5.1.5 on 2025-04-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_atributes_user_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
