name: Run Django Tests in Docker Compose CI

on:
  pull_request:
    branches:
      - dev

    

jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Log in to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t my-django-app ./fad_backend
          
      
      - name: Tag and push Docker image to GHCR
        run: |
          IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker tag my-django-app ghcr.io/$IMAGE_OWNER/my-django-app:latest
          docker push ghcr.io/$IMAGE_OWNER/my-django-app:latest
  lint:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from GHCR
        run: |
          IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/$IMAGE_OWNER/my-django-app:latest

      - name: Run lint (flake8)
        run: |
          IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker run --rm ghcr.io/$IMAGE_OWNER/my-django-app:latest flake8 ./fad_backend
  test:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from GHCR
        run: |
          IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/$IMAGE_OWNER/my-django-app:latest

      - name: Run tests
        run: |
          IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker run --rm \
          ghcr.io/$IMAGE_OWNER/my-django-app:latest \
          bash -c "coverage run manage.py test && coverage report --fail-under=80"
