name: Run Django Tests in Docker Compose CI

on:
  push:
    branches:
      - test_ci

    
jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Check for backend build changes
        id: detect_changes
        run: |
          if git diff --quiet origin/dev...HEAD -- fad_backend/Dockerfile fad_backend/requirements.txt; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        
      - name: Build and push Docker image to GHCR
        if: steps.detect_changes.outputs.changed == 'true'
        run: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
            echo "Building Docker image..."
            docker build -t my-django-app ./fad_backend
        
            echo "Tagging image..."
            IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            docker tag my-django-app ghcr.io/$IMAGE_OWNER/my-django-app:latest
        
            echo "Pushing image to GHCR..."
            docker push ghcr.io/$IMAGE_OWNER/my-django-app:latest
        
  check-lint:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set IMAGE_OWNER environment variable
        run: echo "IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Run tests via Docker Compose
        run: docker compose -f .github/compose/docker-compose.django-lint.yml up --abort-on-container-exit --exit-code-from web
      
      - name: Clean up after test run
        if: always()
        run: docker compose -f .github/compose/docker-compose.django-lint.yml down -v --remove-orphans
  test:
    needs: check-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set IMAGE_OWNER environment variable
        run: echo "IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Run tests via Docker Compose
        run: docker compose -f .github/compose/docker-compose.django-test.yml up --abort-on-container-exit --exit-code-from web
      
      - name: Clean up after test run
        if: always()
        run: docker compose -f .github/compose/docker-compose.django-test.yml down -v --remove-orphans
