name: Run Django Tests in Docker Compose

on:
  push:
    branches: [dev]
    paths:
      - 'fad_backend/**' 


jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-django-app ./fad_backend

      - name: Run lint(flake8)
        run: docker run --rm my-django-app flake8 ./fad_backend

      - name: Run tests
        run: docker run --rm my-django-app coverage run manage.py test && coverage report --fail-under=90
