name: Build and push backend docker image

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'fad_backend/Dockerfile'
      - 'fad_backend/requirements.txt'

    
jobs: 
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Log in to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build -t my-django-app ./fad_backend
          
      
      - name: Tag and push Docker image to GHCR
        run: |
          IMAGE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker tag my-django-app ghcr.io/$IMAGE_OWNER/my-django-app:latest
          docker push ghcr.io/$IMAGE_OWNER/my-django-app:latest